import "./assets/base.css";

import { createApp } from "vue";
import { Icon } from "@iconify/vue";
import App from "./App.vue";
import router from "./router";
import BaseButton from "@/components/Base/BaseButton.vue";
import BaseSubheading from "@/components/Base/BaseSubheading.vue";
import BaseCard from "@/components/Base/BaseCard.vue";
import ProjectDescription from "@/components/UI/ProjectDescription.vue";
import Footer from "@/components/UI/FooterSection.vue";
const app = createApp(App);
app.component("base-button", BaseButton);
app.component("sub-heading", BaseSubheading);
app.component("Icon", Icon);
app.component("base-card", BaseCard);
app.component("project-description", ProjectDescription);
app.component("footer-section", Footer);
app.use(router);
app.mount("#app");
